include:
- template: Auto-DevOps.gitlab-ci.yml

stages:
  - build
  - package
  - test
  - deploy  # dummy stage to follow the template guidelines
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup


build_image:
  image: docker:latest
  stage: package
  services:
    - docker:dind
    
  script:
    - export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
    -  export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
    - export
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Building the image"
    - docker build -t $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG ./app
    - echo "Pushing the image to the registry"
    - docker push $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG
    - echo "Deploying the image to the ACDH-CH Kubernetes over the Gitlab CI/CD AutoDevOps"

#  only:
#   - master
