name: Publish and Deploy

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -t acdhch/hbas .
      - name: docker push
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" 
          docker push acdhch/hbas
  rancher:
     needs: push_to_registry
     name: Deploy to rancher
     runs-on: ubuntu-latest
     steps:
     - name: Rancher Deploy Action
       run: "docker run --rm curlimages/curl:7.74.0  --request POST 'https://rancher.acdh-dev.oeaw.ac.at/p/c-zdbh8:p-h6j6v/workloads/deployment:hbas:hbas?action=redeploy' --header 'Accept: application/json' --header 'Authorization: Bearer ${{ secrets.RANCHER_BARER_TOKEN }}'"
